const UserController = require("../controller/userController")
const router = require("express").Router()
router.get("/", UserController.all)
router.get("/add", UserController.add)
router.get("/addLogic", UserController.addLogic)
router.get("/single", UserController.single)
router.get("/edit",UserController.edit)
router.get("/del", UserController.del)
router.get("/delAll", UserController.delAll)
module.exports=router
